favicon: null
name: Joshua Lenon
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2764157
  lightness: 0.9037566
  brandStrength: 0.3489322091918439
  brandColors:
    - '#405666'
    - '#E7E7E8'
    - '#25282B'
    - '#007EE5'
    - '#4CA3EB'
  rhythmicContrast: 0.6425532
typography_spectrum: 0.1388596135657281
layout_spectrum: 0.2595745
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
