name: Joshua Lenon
favicon: null
layout_spectrum: 0.2595745
typography_spectrum: 0.1388596135657281
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Rising in the West and setting in the East
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#405666'
    - '#E7E7E8'
    - '#25282B'
    - '#007EE5'
    - '#4CA3EB'
  brandStrength: 0.3489322091918439
  lightness: 0.9037566
  saturation: 0.2764157
  rhythmicContrast: 0.6425532
purpose: []
